name: C/C++ CI
on: [push]
jobs:
  compile_normal:
    runs-on: ubuntu-18.04
    steps:
    - name: Pull
      uses: actions/checkout@v1
    - name: Compile to binary
      run: make build
  compile_prometheus:
    runs-on: ubuntu-18.04
    steps:
    - name: Pull
      uses: actions/checkout@v1
    - name: Compile to binary
      run: make build_prometheus

  build_normal:
    name: Build without Prometheus
    if: contains(github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        uses: actions/checkout@master

      - name: Build Docker image
        run: docker build --build-arg buildType=build_static -t lol3r/c-http-server:latest .

      - name: Login to Repo
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish
        run: docker push lol3r/c-http-server:latest
  build_prometheus:
    name: Build with Prometheus
    if: contains(github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        uses: actions/checkout@master

      - name: Build Docker image
        run: docker build --build-arg buildType=build_prometheus_static -t lol3r/c-http-server:latest-prometheus .

      - name: Login to Repo
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish
        run: docker push lol3r/c-http-server:latest-prometheus

  speedTest:
    name: Speedtesting
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        uses: actions/checkout@master

      - name: Compile Binary
        run: make build

      - name: Install SpeedTester
        run: |
          curl -s https://api.github.com/repos/lol3rrr/speedTester/releases/latest | grep "browser_download_url" | grep "linux_x64" | cut -d '"' -f 4 | wget -O speedTester -qi -
          chmod +x speedTester
          sudo cp speedTester /usr/bin/speedTester

      - name: Run Speed Test
        run: make run_speedTest
