name: Benchmarks
on:
  push:
    branches:
      - master
    pull_request:
      - '*'
jobs:
  benchmark:
    name: Benchmarking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Benchmark library
        uses: actions/cache@v1
        with:
          path: libs/benchmark
          key: ${{ runner.os }}-googlebenchmark-v1.5.0
      - name: Run benchmark
        run: make json
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: C++ Benchmark
          tool: 'googlecpp'
          output-file-path: benchmark_result.json
          # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '175%'
          comment-always: true
          comment-on-alert: true
          auto-push: true
          fail-on-alert: true
          alert-comment-cc-users: '@lol3rrr'
